#!/bin/bash
rm -rf m4 autom4te.cache \
          aclocal.m4 \
          stamp-h1 \
          $(find . -name "Makefile") \
          $(find . -name "Makefile.in") \
          missing \
          compile \
          config.guess \
          config.status \
          config.log \
          config.h* \
          config.sub \
          configure \
          depcomp \
          install-sh \
          test-driver \
          libtool \
          ltmain.sh \
          csv-viewer-*.tar.gz \
          coverage.info \
          coverage-report \
          $(find . -name "*.gcno") \
          $(find . -name "*.gcda") \
          $(find . -name "*.o") \
          $(find . -name "*.a")