sonar.projectKey=vepo_csvi
sonar.organization=vepo-github
sonar.sources=src
sonar.host.url=https://sonarcloud.io
sonar.cfamily.gcov.reportsPath=src
sonar.projectVersion=$VERSION
sonar.exclusions=tests/**/*