name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get update && sudo apt install -y libncurses5-dev libncursesw5-dev pkg-config check unzip
    - name: autoreconf
      run: autoreconf -ivf
    - name: Configure with coverage
      run: ./configure --enable-coverage
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'
    - name: Configure Sonar
      run: |
        wget -q https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
        unzip -q build-wrapper-linux-x86.zip
        wget -q https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-7.0.2.4839-linux-x64.zip
        unzip -q sonar-scanner-cli-7.0.2.4839-linux-x64.zip
    - name: Run tests with build wrapper
      run: |
        ./build-wrapper-linux-x86/build-wrapper-linux-x86-64 --out-dir bw-output make clean
        ./build-wrapper-linux-x86/build-wrapper-linux-x86-64 --out-dir bw-output make check
        for source_file in $(find src -name '*.c')
        do
            cd $(dirname "$source_file")
            gcov $(basename "$source_file") || true
            cd -
        done
    - name: Run Sonar
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        VERSION=$(./configure --version | head -n 1 | awk '{print $3}')
        ./sonar-scanner-7.0.2.4839-linux-x64/bin/sonar-scanner \
          -Dsonar.organization=vepo-github \
          -Dsonar.projectKey=csv-viewer \
          -Dsonar.sources=src \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.cfamily.build-wrapper-output=bw-output \
          -Dsonar.login=${SONAR_TOKEN} \
          -Dsonar.cfamily.gcov.reportsPath=src \
          -Dsonar.projectVersion=$VERSION \
          -Dsonar.exclusions=tests/**/*
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Configure release build
      run: ./configure
    - name: Build and test
      run: |
        make clean
        make
        make check
    - name: make dist
      run: make dist
    - name: Upload dist artifact
      uses: actions/upload-artifact@v4
      with:
        name: csv-viewer
        path: csv-viewer-*.tar.gz

  create-installer:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt install -y libncurses5-dev libncursesw5-dev pkg-config check unzip
      - run: bash build-installer
      - uses: actions/upload-artifact@v4
        with:
          name: get-csvi
          path: installer
